### ISSUE TITLE
What license is this code released under?

### ISSUE THREAD

**Issue by dflock** [ricochet1k/vue-blocks#2]
Things that you create and don't specify a license for, are automatically copyrighted to you - and not re-usable by others without explicit permission for each use.

As far as I can see, there's no license specified for this repository, so anyone who wants to use it would need to get permission directly from you for each use.

Is this intentional? If not, you should specify the license, so others can use it.

**Comment by ricochet1k** [comment]
Sorry it took so long, I was trying to figure out copyright with my job. I've decided to attach an Apache 2 License for now, though I'm okay with dual-licensing anyone needs something else.

**Comment by dflock** [comment]
Cool, thanks!
